[theme]
fg = "red"
bg = "default"

[prompt]
lines = [
    "{username} {cwd} -> ",
]

[prompt.cwd]
enabled = true
fg = "magenta"
format = "{cwd} lululul"

[prompt.username]
enabled = true
fg = "yellow"
format = "👑{username}👑"