[theme]
fg = "red"
bg = "default"

[prompt]
lines = [
    "{cwd} ({git}) {ram}",
    "{username}@{hostname} -> ",
]

[prompt.cwd]
fg = "magenta"
format = "{cwd}"

[prompt.username]
fg = "yellow"
format = "👑{username}👑"

[prompt.git]
format = "{branch}{dirty}"


[prompt.date]
format = "{DD}-{MM}-{YYYY}"

[prompt.ram]
enabled = true
format = "{used}/{total}"